### ISSUE TITLE
PWM disturbs the interrupt

### ISSUE THREAD

**Issue by Franzelfx** [Franzelfx/openventilator#1]
## The problem

PWM has an effect on interrupt for rpm of the motor.

**Problem Type**

- [x] Software
- [ ] Design
- [ ] Research

## Details

If the duty cycle of the PWM is set, an Interrupt is triggered and results in an incorrect calculation of the current rpm.

**Comment by Franzelfx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SOFTWARE - Speed control of the cycle based on encoder and end switch](https://trello.com/c/JM67JtUR/14-software-speed-control-of-the-cycle-based-on-encoder-and-end-switch)

**Comment by 1endell** [comment]
Man, can you show how you did the math? Maybe i can help

**Comment by Franzelfx** [comment]
The math is in the function "calculate()" in followed file:
https://github.com/Franzelfx/openventilator/blob/master/07_Software/src/rotarySensor.cpp

**Comment by Franzelfx** [comment]
It wasn't a software problem. I forgot the flyback diode -_-.
